name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set up job
        run: echo "Setting up job"
        
      - name: Run actions/checkout@v2
        uses: actions/checkout@v2
        
      - name: Build the Docker image
        run: |
          echo "Building the Docker image"
          docker build -t mallen5/rest:v0.0.1 .
        
      - name: Run the Docker container
        run: |
          echo "Running the Docker container"
          docker run -d --name microservice mallen5/rest:v0.0.1
        
      - name: Test the RESTful service
        run: |
          echo "Testing the RESTful service"
          sleep 5
          curl http://localhost:5000/fib?length=10
          # Add more curl commands to verify other endpoints if needed
          
      - name: Post Run actions/checkout@v2
        uses: actions/checkout@v2
        run: echo "Post-run actions/checkout@v2"
        
      - name: Complete job
        run: echo "Job complete"
